### ISSUE TITLE
Падение бенчмаркинга OpenVINO в Docker

### ISSUE THREAD

**Issue by FenixFly** [itlab-vision/dl-benchmark#382]
После последних коммитов началось падение бенчмаркинга. 

**Лог запуска и ошибки на машине i7. Падает 6й по счету тест**

```
Start inference test on model: alexnet
Command line is: python3 /tmp/dl-benchmark/src/inference/inference_async_mode.py -m /mnt/models/public/alexnet/FP32/alexnet.xml -w /mnt/models/public/alexnet/FP32/alexnet.bin -i /tmp/itlab-vision-dl-benchmark-data/Datasets/ImageNET/ -b 8 -d CPU -ni 1000 --raw_output true
[33;20m[ WARNING ] Inference test on model: alexnet was ended with error. Process logs:[0m
[31;20m[ ERROR ] Inference failed with exception: sequence item 7: expected str instance, NoneType found[0m
Traceback (most recent call last):
  File "inference_benchmark.py", line 80, in inference_benchmark
    test_process.execute()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 59, in execute
    self.__save_failed_test_log()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 153, in __save_failed_test_log
    log_filename = self.__make_log_filename()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 174, in __make_log_filename
    filename = '_'.join(test_settings)
TypeError: sequence item 7: expected str instance, NoneType found
Saving test result in file
[31;20m[ ERROR ] Uncaught exception: 'NoneType' object has no attribute 'get_status'. Traceback: ['  File "inference_benchmark.py", line 114, in <module>\n    inference_status = inference_benchmark(args.executor_type, test_list,\n', '  File "inference_benchmark.py", line 92, in inference_benchmark\n    output_handler.add_row_to_table(process_executor, test, test_process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/output.py", line 57, in add_row_to_table\n    report_row = self.__create_table_row(executor, test, process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/output.py", line 36, in __create_table_row\n    report = test.get_report(process=process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/openvino/openvino_test.py", line 7, in get_report\n    if process.get_status() == 0 and not tensors_num:\n'][0m
```

**Лог запуска и ошибки на машине i3. Падает 79й по счету тест**

```
Start inference test on model: inception-resnet-v2-tf
Command line is: python3 /tmp/dl-benchmark/src/inference/inference_sync_mode.py -m /mnt/models/public/inception-resnet-v2/FP32/inception-resnet-v2-tf.xml -w /mnt/models/public/inception-resnet-v2/FP32/inception-resnet-v2-tf.bin -i /tmp/itlab-vision-dl-benchmark-data/Datasets/ImageNET/ -b 1 -d CPU -ni 1000 --raw_output true
[33;20m[ WARNING ] Inference test on model: inception-resnet-v2-tf was ended with error. Process logs:[0m
[31;20m[ ERROR ] Inference failed with exception: sequence item 7: expected str instance, NoneType found[0m
Traceback (most recent call last):
  File "inference_benchmark.py", line 80, in inference_benchmark
    test_process.execute()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 59, in execute
    self.__save_failed_test_log()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 153, in __save_failed_test_log
    log_filename = self.__make_log_filename()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 174, in __make_log_filename
    filename = '_'.join(test_settings)
TypeError: sequence item 7: expected str instance, NoneType found
Saving test result in file
[31;20m[ ERROR ] Uncaught exception: 'NoneType' object has no attribute 'get_status'. Traceback: ['  File "inference_benchmark.py", line 114, in <module>\n    inference_status = inference_benchmark(args.executor_type, test_list,\n', '  File "inference_benchmark.py", line 92, in inference_benchmark\n    output_handler.add_row_to_table(process_executor, test, test_process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/output.py", line 57, in add_row_to_table\n    report_row = self.__create_table_row(executor, test, process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/output.py", line 36, in __create_table_row\n    report = test.get_report(process=process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/openvino/openvino_test.py", line 7, in get_report\n    if process.get_status() == 0 and not tensors_num:\n'][0m
```

**Лог запуска и ошибки на машине tower**

```
Command line is: python3 /tmp/dl-benchmark/src/inference/inference_sync_mode.py -m /mnt/models/public/inception-resnet-v2/FP32/inception-resnet-v2-tf.xml -w /mnt/models/public/inception-resnet-v2/FP32/inception-resnet-v2-tf.bin -i /tmp/itlab-vision-dl-benchmark-data/Datasets/ImageNET/ -b 1 -d CPU -ni 1000 --raw_output true
[33;20m[ WARNING ] Inference test on model: inception-resnet-v2-tf was ended with error. Process logs:[0m
[31;20m[ ERROR ] Inference failed with exception: sequence item 7: expected str instance, NoneType found[0m
Traceback (most recent call last):
  File "inference_benchmark.py", line 80, in inference_benchmark
    test_process.execute()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 59, in execute
    self.__save_failed_test_log()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 153, in __save_failed_test_log
    log_filename = self.__make_log_filename()
  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/processes.py", line 174, in __make_log_filename
    filename = '_'.join(test_settings)
TypeError: sequence item 7: expected str instance, NoneType found
Saving test result in file
[31;20m[ ERROR ] Uncaught exception: 'NoneType' object has no attribute 'get_status'. Traceback: ['  File "inference_benchmark.py", line 114, in <module>\n    inference_status = inference_benchmark(args.executor_type, test_list,\n', '  File "inference_benchmark.py", line 92, in inference_benchmark\n    output_handler.add_row_to_table(process_executor, test, test_process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/output.py", line 57, in add_row_to_table\n    report_row = self.__create_table_row(executor, test, process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/output.py", line 36, in __create_table_row\n    report = test.get_report(process=process)\n', '  File "/home/itmm/dli-jenkins-worker/dl-benchmark/src/benchmark/frameworks/openvino/openvino_test.py", line 7, in get_report\n    if process.get_status() == 0 and not tensors_num:\n'][0m
```

**Comment by valentina-kustikova** [comment]
@FenixFly, нужен конфигурационный файл бенчмарка, на котором происходит падение.

**Comment by maslovaz** [comment]
@FenixFly посмотрите, пожалуйста, этот фикс https://github.com/itlab-vision/dl-benchmark/pull/384
должно починить создание файла с логом

**Comment by FenixFly** [comment]
@maslovaz спасибо, помогло!
