### ISSUE TITLE
Ошибка при попытке прочитать Конфиг с помощью мейкера конфигов

### ISSUE THREAD

**Issue by FenixFly** [itlab-vision/dl-benchmark#383]
```bash
(openvino) D:\dl-benchmark-vasilev\src\config_maker>python main.py

Traceback (most recent call last):
  File "D:\dl-benchmark-vasilev\src\config_maker\presenter\benchmark_config_presenter.py", line 43, in __handle_load_button
    models, data = self.__model.benchmark_config.parse_config(path_to_config)
  File "D:\dl-benchmark-vasilev\src\config_maker\model\benchmark_config\benchmark_config.py", line 45, in parse_config
    test = Test.parse(dom)
  File "D:\dl-benchmark-vasilev\src\config_maker\model\benchmark_config\test.py", line 78, in parse
    model = Model.parse(dom)[0]
  File "D:\dl-benchmark-vasilev\src\config_maker\model\models\model.py", line 95, in parse
    model_path = parsed_model.getElementsByTagName(CONFIG_MODEL_PATH_TAG)[0].firstChild.data
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by valentina-kustikova** [comment]
@FenixFly, сейчас сильно поменялся конфигурационный файл бенчмарка, поэтому необходимо актуализировать реализацию config_maker.

@a-sidorova

**Comment by FenixFly** [comment]
После последних изменений не воспроизводится, поэтому закрываю
