### ISSUE TITLE
При записи в JSON ошибки

### ISSUE THREAD

**Issue by FenixFly** [itlab-vision/dl-benchmark#429]
Если инференс завершается с ошибкой, то log файл создается под одним названием, а результаты записаться пытаются в другой. Ловил недавно такую ошибку при работе с докером, но тут она в смоук-тесте попала.

Пример возникновения ошибки тут (создает файл `mobilenet-v1-1.0-224-tf_TensorFlow_CPU_default_1_2023-11-01_22-25-05.log` но пытается записать в `tensorflow_python_benchmark_mobilenet-v1-1.0-224-tf_01.11.23_22-25-03.json`)
https://github.com/itlab-vision/dl-benchmark/actions/runs/6725769129/job/18280796660?pr=427

```
Traceback (most recent call last):
  File "/home/runner/work/dl-benchmark/dl-benchmark/src/inference/inference_tensorflow.py", line 19, in <module>
    from src.model_converters.tf2tflight.tensorflow_common import (load_model, get_gpu_devices, is_gpu_available,  # noqa
ModuleNotFoundError: No module named 'src.model_converters.tf2tflight'
Process returncode = 1
[ WARNING ] Inference test on model: mobilenet-v1-1.0-224-tf was ended with error. Process logs: ["2023-11-01 22:25:03.952155: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib\n", '2023-11-01 22:25:03.952182: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n', 'Traceback (most recent call last):\n', '  File "/home/runner/work/dl-benchmark/dl-benchmark/src/inference/inference_tensorflow.py", line 19, in <module>\n', '    from src.model_converters.tf2tflight.tensorflow_common import (load_model, get_gpu_devices, is_gpu_available,  # noqa\n', "ModuleNotFoundError: No module named 'src.model_converters.tf2tflight'\n"]
Save failed test log to /home/runner/work/dl-benchmark/dl-benchmark/test/smoke_test/mobilenet-v1-1.0-224-tf_TensorFlow_CPU_default_1_2023-11-01_22-25-05.log
[ ERROR ] Test finished with non-zero code: 1
Saving test result in file
[ ERROR ] Uncaught exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/dl-benchmark/dl-benchmark/test/smoke_test/logs/tensorflow_python_benchmark_mobilenet-v1-1.0-224-tf_01.11.23_22-25-03.json'.
Traceback:
  File "../../src/benchmark/inference_benchmark.py", line 114, in <module>
    inference_status = inference_benchmark(args.executor_type, test_list,
  File "../../src/benchmark/inference_benchmark.py", line 92, in inference_benchmark
    output_handler.add_row_to_table(process_executor, test, test_process)
  File "/home/runner/work/dl-benchmark/dl-benchmark/src/benchmark/output.py", line 59, in add_row_to_table
    report_row = self.__create_table_row(executor, test, process)
  File "/home/runner/work/dl-benchmark/dl-benchmark/src/benchmark/output.py", line 37, in __create_table_row
    report = test.get_report(process=process)
  File "/home/runner/work/dl-benchmark/dl-benchmark/src/benchmark/frameworks/config_parser/test_reporter.py", line 17, in get_report
    json_report_content = process.get_json_report_content()
  File "/home/runner/work/dl-benchmark/dl-benchmark/src/benchmark/frameworks/processes.py", line 90, in get_json_report_content
    return json.loads(self._executor.get_file_content(self.report_path))
  File "/home/runner/work/dl-benchmark/dl-benchmark/src/benchmark/executors.py", line 47, in get_file_content
    with open(path) as file:

inference_benchmark exited with non-zero code: 1
```

@n-berezina-nn  @maslovaz помогите пожалуйста с тем, чтобы у json создавались правильные имена.

**Comment by n-berezina-nn** [comment]
@FenixFly насколько я помню, файл mobilenet-v1-1.0-224-tf_TensorFlow_CPU_default_1_2023-11-01_22-25-05.log содержит логи упавшего теста для удобства дебага.
В вашем случае в файл /home/runner/work/dl-benchmark/dl-benchmark/test/smoke_test/logs/tensorflow_python_benchmark_mobilenet-v1-1.0-224-tf_01.11.23_22-25-03.json ничего не пишется, потому что до этого в скрипте инференса просто не доходит тк не проходит импорт библиотеки.
при этом скрипт inference_benchmark.py все равно пытается читать файл, тк запись в csv там прооисходит безусловно от статусы инференса. файла нет и он падает.
Проблемы с именованием логов нет.

**Comment by FenixFly** [comment]
Понял, спасибо

**Comment by n-berezina-nn** [comment]
@FenixFly закрываем issue?

**Comment by FenixFly** [comment]
> @FenixFly закрываем issue?

Да, хорошо
